### ISSUE TITLE
Didn't initalize with packages.json file

### ISSUE THREAD

**Issue by ajbraus** [thewildpendulum/gaps#1]

**Comment by thewildpendulum** [comment]
Thanks for taking the time to file an issue. I try to fix bugs as soon as they come up, and a little more information would really help.

**Comment by robinbijlani** [comment]
I am running into the same issue. Made a blank Phonegap project via CLI and added Android platform. Navigated to platforms/android/assets, and ran the generator and `bower install`. That went fine, but during `npm install`: 

$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open 'c:\xampp\htdocs\eiramp2\platforms\android\assets\p
ackage.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodej
s\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd c:\xampp\htdocs\eiramp2\platforms\android\assets
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path c:\xampp\htdocs\eiramp2\platforms\android\assets\package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\xampp\htdocs\eiramp2\platforms\android\assets\npm-debug.log
npm ERR! not ok code 0

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'c:\Program Files\nodejs\node.exe',
1 verbose cli   'c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.3.11
3 info using node@v0.10.21
4 error install Couldn't read dependencies
5 error Error: ENOENT, open 'c:\xampp\htdocs\eiramp2\platforms\android\assets\package.json'
6 error If you need help, you may report this log at:
6 error     http://github.com/isaacs/npm/issues
6 error or email it to:
6 error     npm-@googlegroups.com
7 error System Windows_NT 6.1.7601
8 error command "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
9 error cwd c:\xampp\htdocs\eiramp2\platforms\android\assets
10 error node -v v0.10.21
11 error npm -v 1.3.11
12 error path c:\xampp\htdocs\eiramp2\platforms\android\assets\package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]

**Comment by iamlasse** [comment]
It also doesnt generate an index.js file and there is no app variable with an attached initialize function ...

**Comment by thewildpendulum** [comment]
Sorry for the wait, guys. Fixed in 5377460279.

**Comment by thewildpendulum** [comment]
@iamlasse PhoneGap generates its own `index.js` and initializes itself. This project only modifies `index.html` to include the angular scripts and demo markup.
